version: '3.4'

services:
  spotifydwapi:
    image: spotifydwapi
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        MASHINE: ${MASHINE}
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
    volumes:
      - ./data:/app/data:rw
      - ./certbot:/app/certbot:ro