[tool.poetry]
name = "spotify_dw_api"
version = "0.1.0"
description = ""
authors = ["WildElaeagnus <54314123+akorzunin@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = "^3.10"
spotipy = "^2.20.0"
python-dotenv = "^0.20.0"
uvicorn = "^0.18.1"
pydantic = "^1.9.1"
Jinja2 = "^3.1.2"
tinydb = "^4.7.0"
schedule = "^1.1.0"
APScheduler = "^3.9.1.post1"
fastapi-mail = "^1.2.2"
fastapi-sessions = "^0.3.2"
fastapi = "0.87.0"
email-validator = "^1.3.0"

[tool.poetry.dev-dependencies]
arel = "^0.2.0"
websockets = "^10.3"
black = {version = "^22.6.0", allow-prereleases = true}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
